apiVersion: v1
kind: Service
metadata:
  name: ekscluster-service
  labels:
    app: registrationapp 
spec:
  selector:
    app: registrationapp 

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
