apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ekscluster-registrationapp
  labels: 
     app: registrationapp

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: registrationapp

  template:
    metadata:
      labels:
        app: registrationapp
    spec:
      containers:
      - name: registrationapp
        image: tanu2802/registrationapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
